---
# handlers file for mariadb-galera-cluster
- name: "restart mariadb"
  service:
    name: "mariadb"
    state: "restarted"
  become: true

- name: "reload maridb"
  service:
    name: "mariadb"
    state: "reloaded"
  become: true
