---
# VERSION OPTS
ZOOKEEPER_UI_VERSION: 2.2

BUILDS_FILES_PATH: /tmp

# URLS
ZOOKEEPER_UI_URL: "https://github.com/DeemOpen/zkui/archive/{{ ZOOKEEPER_UI_VERSION }}.tar.gz"

# PATHS
ZOOKEEPER_UI_PATH: /opt/zookeeper-ui

#Setting
ZOOKEEPER_UI_USER: zookeper-ui
ZOOKEEPER_UI_GROUP: "{{ ZOOKEEPER_UI_USER }}"
ZOOKEEPER_UI_PORT: 9090
ZOOKEEPER_UI_SERVERS: "zk1:2181,zk2:2181,zk3:2181"

ZOOKEEPER_UI_JAVAHOME: /opt/java/jdk_1.8.0_121