- name: reload systemd
  command: systemctl daemon-reload

- name: reload initctl
  command: initctl reload-configuration

- name: restart proftpd
  systemd:
    state: restarted
    daemon_reload: yes
    name: proftpd

- name: restart firewalld
  systemd:
    state: restarted
    name: fiewalld