---
- name: Open the correct IPTables ports
  lineinfile:
    dest: /etc/sysconfig/iptables
    regexp: "^-A INPUT -m state --state {{item.states}} -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
    line: "-A INPUT -m state --state {{item.states}} -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT"
#    insertafter="^:OUTPUT ACCEPT \[\d*:\d*\]$"
    insertbefore: "^-A INPUT -j REJECT --reject-with icmp-host-prohibited$"
  with_items:
    - { states: NEW, protocol: tcp, port: 2224 }
    - { states: NEW, protocol: tcp, port: 3121 }
    - { states: NEW, protocol: tcp, port: 11111 }
    - { states: NEW, protocol: tcp, port: 21064 }
    - { states: NEW, protocol: udp, port: 5404 }
    - { states: NEW, protocol: udp, port: 5405 }

#- name: Copy iptables configuration
#  copy:
#   src: iptables
#   dest: /etc/sysconfig/iptables
#   owner: root
#   group: root
#  notify:
#    - restart iptables

- name: Enable and start iptables service
  service:
   name: iptables
   enabled: yes
   state: started

- meta: flush_handlers
