---
- name: install | Add PostgreSQL repository
  yum:
    name: "{{ postgresql_yum_repository_url }}"
    state: present

- name: install | Make sure the dependencies are installed
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
   - "python-psycopg2"
   - "python-pycurl"
   - "glibc-common"

- name: install | Install PostgreSQL
  yum:
    name: "{{ item }}"
    state: present
  environment: "{{ postgresql_env }}"
  with_items:
    - "postgresql{{ postgresql_version_terse }}-server"
    - "postgresql{{ postgresql_version_terse }}"
    - "postgresql{{ postgresql_version_terse }}-contrib"
    - "postgresql{{ postgresql_version_terse }}-libs"

#- name: PostgreSQL | PGTune
#  yum:
#    name: pgtune
#    state: present
#  environment: "{{ postgresql_env }}"
#  when: postgresql_pgtune

