---
# tasks file for ambari stack role

#- name: "RedHat | checking if ambari server configured "
#  stat:
#    path: "/etc/ambari.done"
#  register: "ambari_configured"

- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
    priority: " {{ item.priority | default('20') }}"
  with_items: "{{ ambari_repo_yum }}"
  tags:
    - ambari-server
    - ambari-agent
    - ambari-metrics
    - grafana

# ambari server install
- include: ambari-server.yml
  tags:
    - ambari-server

# ambari agent install
- include: ambari-agent.yml
  tags:
    - ambari-agent

# ambari metric install
- include: ambari-metrics.yml
  tags:
    - ambari-metrics
